### PR TITLE
Use numba to boost performance of pima test

### PR DESCRIPTION
**Pull request by bourgesl**
I tried numba to optimize runtime performance (llvm) in your pima test.

It is going a lot faster: 15 times !
nb_epochs= 200

- pima.py:
user	0m33,646s

- pima_numba.py:
user	0m2,381s

### CODE REVIEW

**Comment by Deyht** [comment]
Hi, nice call for np.sum, some was numpy in the code and some was regular sum

I can not get numba to work on my side as it suspects an incompatibility with np.shape()
Anyway, as the code is only pedagogical, and expected to run with minimum package installation, i will not add it by default but rater add the corresponding lines as comments so user can 'opt in' easily.

Thanks for the addition !

**Comment by Deyht** [comment]
It seems that it is the nopython=True option that causes the conflict with numpy shape on my install. It is still significantly faster with this option to false, which will be helpful for sgd and on-line codes !

**Comment by bourgesl** [comment]
I have no problem on my machine and tried porting spectra_sgd: it complains about compiling print() statements ... will check what are the jit arguments .

I just wanted to show numba nice improvements and it is more 'eco-friendly' and fluent: it is easier to play with your code samples.

**Comment by Deyht** [comment]
I have slightly modified the code so it is not using np.shape inside the compiled functions anymore. Numba work like a charm now.
My guess is that compiling forward and backward should be enough overall, they contain the vast majority of the recurrent computation (the confmat function is only called every 10 or more epochs and is pretty lightway).

To speed up the exploration of the hyperparameters for the stellar spectra dataset it is also possible to take just half the pixels for the spectra (one every two).

Completely agree about the "eco friendly" aspect, even if my main advise about it would be to not use python for computation heavy tasks at all (interfaces with C and Fortran are not that hard to construct to keep the user friendly interface that python propose).

**Pull request closed without merging**
